config/routes.rb
Rails.application.routes.draw do

  resources :heros do # Because Rails doesn't know how to pluralize hero
    resources :undoables
  end
  resources :days
  resources :unscheduled_days

  get '/:year/:month' => 'schedule#index', as: :schedule

  root 'schedule#index'

end

app/models/day.rb
class Day < ActiveRecord::Base
  ERROR_THRESHOLD = 365
  class UnreconciledDayError < ArgumentError; end

  validate :is_not_holiday?
  validate :is_not_weekend?
  belongs_to :hero
  has_many :undoable_days

  default_scope { order(:date) }

  class << self
    def after_today
      where('date > ?', Date.today)
    end

    def surrounding_range(date, count_of_days)
      where(date: ((date - count_of_days.days)..(date + count_of_days.days)))
    end

    def next_valid(date:)
      while(!new(date: date).valid?)
        date = date + 1.day
      end
      find_or_create_by(date: date)
    end
  end

  def swap(day)
    hero = self.hero
    self.hero = day.hero
    day.hero = hero

    day.save
    save

    day
  end

  ##
  # This is a fairly simplistic algorithm, it is quite possible to lock
  # such an algorithm outside of the explored range (the 40 days given)
  #
  # Multi-person algorithms are definitely possible but could be an
  # entire discussion in and of themselves.
  def progressive_find
    swap = false
    range = 7
    while(!swap)
      check_excess_range(range)
      available_days = swappable_days(range)
      if available_days.count > 0
        return available_days
      end
      range *= 2
    end
  end

  def swappable_days(range=nil)
    @restricted_users ||= undoable_days.pluck(:hero_id)
    available_days = self.class
                         .after_today
                         .where.not(hero_id: @restricted_users)
                         .where.not(hero_id: hero_id)
    available_days = available_days.surrounding_range(date, range) if range
    available_days.all
  end

  def find_and_swap
    closest_available_days = progressive_find
    swap(closest_available_days.shuffle.first)
  end

  def next_valid
    self.class.next_valid(date: (date + 1.day))
  end

  def hero
    super || NullHero.new
  end

  private

  def check_excess_range(range)
    if range > ERROR_THRESHOLD
      raise UnreconciledDayError, "Cannot find a hero D:"
    end
  end

  def is_holiday?
    ExactHoliday.check(date) ||
      RelativeHoliday.check(date)
  end

  def is_weekend?
    [0,6].include?(date.wday)
  end

  def is_not_holiday?
    if is_holiday?
      errors.add(:date, "day is a holiday")
    end
  end

  def is_not_weekend?
    if is_weekend?
      errors.add(:date, "day is weekend")
    end
  end
end

app/models/exact_holiday.rb
class ExactHoliday < ActiveRecord::Base
  validate :valid_date?

  class << self
    def check(date)
      exists?(month: date.month, day: date.day)
    end
  end

  def valid_date?
    return true if (month == 2 && day == 29) # Leap Year acceptance
    Date.new(Date.today.year, month, day)
  rescue ArgumentError => e
    if e.message == "invalid date"
      if month < 1 || month > 12
        errors.add(:month, "invalid month")
      else
        errors.add(:day, "invalid day, or invalid day for month")
      end
    else
      raise e
    end
  end
end

app/models/hero.rb
class Hero < ActiveRecord::Base
  has_many :days
  has_many :undoable_days, dependent: :destroy

  def undoable(day)
    day.find_and_swap
    self.undoable_days.create(day: day)
  end
end

app/models/null_hero.rb
class NullHero
  def name
    "Nobody"
  end

  def undoable_days
    []
  end

  def undoable(*); end

  def days
    Day.unscoped.where(hero_id: nil)
  end
end

app/models/relative_holiday.rb
class RelativeHoliday < ActiveRecord::Base
  validates :occurrence, inclusion: { in: %w(first second third fourth last) }
  validates :day_of_week, inclusion: { in: (0..6) }
  validates :month, inclusion: { in: (1..12) }

  class << self
    def check(date)
      holidays = RelativeHoliday.where(month: date.month, day_of_week: date.wday, offset: 0)
      holidays.each do |holiday|
        return true if date == holiday.for_year(date.year)
      end
      relative_to_relative = RelativeHoliday.where(month: date.month).where.not(offset: 0)
      relative_to_relative.each do |holiday|
        return true if date == holiday.for_year(date.year)
      end

      false
    end
  end

  def for_year(year)
    send("#{occurrence}_given_day_of_month", year)
  end

  def first_given_day_of_month(year)
    date = Date.new(year, self.month)
    weekday_of_first_day = date.wday
    modifier = if self.day_of_week == weekday_of_first_day
                 0
               elsif self.day_of_week > weekday_of_first_day
                 self.day_of_week - weekday_of_first_day
               else
                 (7 - weekday_of_first_day) + self.day_of_week
               end
    date + modifier.days + offset.days
  end

  def second_given_day_of_month(year)
    first_given_day_of_month(year) + 1.week
  end

  def third_given_day_of_month(year)
    first_given_day_of_month(year) + 2.weeks
  end

  def fourth_given_day_of_month(year)
    first_given_day_of_month(year) + 3.weeks
  end

  def last_given_day_of_month(year)
    date = fourth_given_day_of_month(year)
    if (date + 1.week).month == self.month
      date + 1.week
    else
      date
    end
  end
end

app/models/undoable_day.rb
class UndoableDay < ActiveRecord::Base
  belongs_to :hero
  belongs_to :day
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :collect_today

  def collect_today
    @today = Day.find_or_create_by(date: Date.today)
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  def edit
    @day = Day.find(params[:id])
    @swappable_days = @day.swappable_days
  end

  def update
    day = Day.find(params[:id])
    hero = day.hero # Held onto to ensure proper hero for redirect.
    swapping_day = Day.find(params[:swap_id])
    day.swap(swapping_day)
    redirect_to hero_path(hero)
  end
end

app/controllers/heros_controller.rb
class HerosController < ApplicationController
  def index
    @heros = Hero.all
  end

  def show
    @hero = Hero.find(params[:id])
    @days = @hero.days
  end
end

app/controllers/schedule_controller.rb
class ScheduleController < ApplicationController
  def index
    if params[:year].present? && params[:month].present?
      date = Date.new(params[:year].to_i, params[:month].to_i)
    else
      date = Date.today
    end
    @next = date + 1.month
    @prev = date - 1.month
    @days = Day.where(date: date.beginning_of_month..date.end_of_month)
               .where.not(hero_id: nil)
  end
end

app/controllers/undoables_controller.rb
class UndoablesController < ApplicationController
  def index
    @hero = Hero.find(params[:hero_id])
    @undoable_days = @hero.undoable_days.map(&:day)
  end

  def create
    hero = Hero.find(params[:hero_id])
    day = Day.find(params[:day_id])
    hero.undoable(day)
    redirect_to hero_path(hero)
  end

  def destroy
    hero = Hero.find(params[:hero_id])
    undoable_day = hero.undoable_days.find(params[:id])
    day = undoable_day.day
    undoable_day.destroy
    day.update_attribute(:hero_id, hero.id)
    redirect_to hero_path(hero)
  end
end

app/controllers/unscheduled_days_controller.rb
class UnscheduledDaysController < ApplicationController
  def index
    nobody = NullHero.new
    @unassigned_days = nobody.days
  end

  def edit
    @day = Day.find(params[:id])
    restricted_heroes = @day.undoable_days.pluck(:hero_id)
    if restricted_heroes.present?
      @heroes = Hero.where.not(id: restricted_heroes)
    else
      @heroes = Hero.all
    end
  end

  def update
    day = Day.find(params[:id])
    day.update_attribute(:hero_id, params[:day][:hero_id])
    redirect_to unscheduled_days_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/days/_day.html.erb
<div class="day day-<%= day.date.wday %>">
  <h3><%= day.date %></h3>
  <%= render partial: link_bar, locals: {day: day} %>
</div>

app/views/days/_unassigned_actions.html.erb
<p>
  <%= link_to "Assign", edit_unscheduled_day_path(day.id) %>
</p>

app/views/days/_undoable_day_actions.html.erb
<p>
  <%= link_to "Redeem My Honor", hero_undoable_path(@hero.id, day.id), method: :delete %>
</p>

app/views/days/_user_actions.html.erb
<p>
  <%= link_to "Swap", edit_day_path(day.id) %>
  <%= link_to "Undoable", hero_undoables_path(@hero.id, day_id: day.id), method: :post %>
</p>

app/views/days/_user_link.html.erb
<p><%= link_to day.hero.name, hero_path(day.hero) %></p>

app/views/days/edit.html.erb
<h2>Swap <%= @day.date %></h2>
<% @swappable_days.each do |day| %>
  <div>
    <h3><%= day.date %></h3>
    <p><%= day.hero.name %></p>
    <p><%= link_to "Swap", day_path(@day, swap_id: day.id), method: :put %></p>
  </div>
<% end %>

app/views/heros/index.html.erb
<h2>Hero Listing</h2>

<% @heros.each do |hero| %>
  <h3><%= link_to hero.name, hero %></h3>
<% end %>

app/views/heros/show.html.erb
<h2><%= @hero.name %>'s Heroic Days</h2>
<p><%= link_to "Undoable Days", hero_undoables_path(@hero.id) %></p>
<%= render partial: "days/day", collection: @days, locals: {link_bar: "days/user_actions"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SupportHero</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1><%= link_to "Support Hero Schedule", root_path %></h1>
    <nav>
      <ul>
        <li><%= link_to "Heroes", heros_path %></li>
        <li><%= link_to "Unassigned Days", unscheduled_days_path %></li>
      </ul>
    </nav>
  </header>
  <section>
    <h1><%= @today.hero.name %> is Today's Support Hero</h1>
  </section>
<%= yield %>

</body>
</html>

app/views/schedule/index.html.erb
<h2>Calendar View</h2>
<p>
<%= link_to "Prev", schedule_path(year: @prev.year, month: @prev.month) %>
<%= link_to "Next", schedule_path(year: @next.year, month: @next.month) %>
</p>
<%= render partial: "days/day", collection: @days, locals: {link_bar: "days/user_link"} %>

app/views/undoables/index.html.erb
<h2><%= @hero.name %>'s Days of Shame</h2>
<%= render partial: "days/day", collection: @undoable_days, locals: {link_bar: "days/undoable_day_actions"} %>

app/views/unscheduled_days/edit.html.erb
<h2>Who Will Be The Hero For <%= @day.date %>?</h2>
<%= form_tag unscheduled_day_path(@day.id), method: :put do %>
  <%= label(:day, :hero_id, "Hero") %>
  <%= select(:day, :hero_id) do %>
    <%= options_from_collection_for_select(@heroes, 'id', 'name') %>
  <% end %>
  <%= submit_tag("Save the Day") %>
<% end %>

app/views/unscheduled_days/index.html.erb
<h2>Days We Need a Hero!</h2>
<%= render partial: "days/day", collection: @unassigned_days, locals: {link_bar: "days/unassigned_actions"} %>